### ISSUE TITLE
Improve view/controller context

### ISSUE THREAD

**Issue by j-f1** [ArtOfCode-/nails#12]
- [x] [Pass the `locals` in the view as context (:rabbit2:)](https://github.com/ArtOfCode-/nails/projects/1#card-2507756)
- [x] [Parse querystrings](https://github.com/ArtOfCode-/nails/projects/1#card-2507749) 
- [x] [Querystrings with nested objects and arrays using `x[]`](https://github.com/ArtOfCode-/nails/projects/1#card-2507752)
- [x] [Set custom headers](https://github.com/ArtOfCode-/nails/projects/1#card-2507744)
- [x] [Throw on double-renders](https://github.com/ArtOfCode-/nails/projects/1#card-2507746)
- [x] [Caching](https://github.com/ArtOfCode-/nails/issues/15)
- [x] [Streaming](https://github.com/ArtOfCode-/nails/issues/13)
- [ ] [Flashes](https://github.com/ArtOfCode-/nails/projects/1#card-2507716)
- [x] [HTTP Authentication](https://github.com/ArtOfCode-/nails/projects/1#card-2507712)
- [ ] [Implicit Rendering](https://github.com/ArtOfCode-/nails/projects/1#card-2507717)
- [x] [`redirectBack`](http://api.rubyonrails.org/classes/ActionController/Redirecting.html#method-i-redirect_back)
- [ ] [CSRF](https://github.com/ArtOfCode-/nails/projects/1#card-2507719)
- [ ] [`urlFor`](https://github.com/ArtOfCode-/nails/projects/1#card-2507722)

**Comment by ArtOfCode-** [comment]
What do you need me to do?

Also, a note: we don't *have* to support HTTPS, because nginx can happily sit in front of a nails server - that's how DSS works.

**Comment by j-f1** [comment]
I added you to let you know that you can work on anything in the TODO column.
