### ISSUE TITLE
Cache-Control

### ISSUE THREAD

**Issue by j-f1** [ArtOfCode-/nails#15]
- [x] `cache`
- [x] `cache.disable()`
- [x] `cache.enable()`
- ~`cache.store`~
- [x] `cache.expiresNow()`
-  ~`cache.freshWhen`~
- [x] `cache.forever()`
- [x] `cache.expires_` (need to add a `set` handler)
- [x] `cache.maxAge`

**Comment by wfrg342fd** [comment]
You kicked me many times from all over StackExchange since 2011 especially from the JS room but I'm not going away before ironing out my skills or being given another opportunity to show I'm not the one who started the problem.

**Comment by wfrg342fd** [comment]
You kicked me many times from all over StackExchange since 2011 especially from the JS room but I'm not going away before ironing out my skills or being given another opportunity to show I'm not the one who started the problem.

**Comment by wfrg342fd** [comment]
You kicked me many times from all over StackExchange since 2011 especially from the JS room but I'm not going away before ironing out my skills or being given another opportunity to show I'm not the one who started the problem.
