### ISSUE TITLE
Add database/model functionality

### ISSUE THREAD

**Issue by ArtOfCode-** [ArtOfCode-/nails#5]
Like Rails, Nails should have models and a database backend available (preferably optional). The models should be available in controllers *and* views.

**Comment by j-f1** [comment]
@ArtOfCode- Do we really need this? It’s pretty easy to `require()` a custom DB engine, then use it in controllers. Since controllers can be `async function`s, people can use [sequelize](https://github.com/sequelize/sequelize) pretty seamlessly.

**Comment by ArtOfCode-** [comment]
I'd like to have it, yeah. We can leave the option open to require a custom engine, but ideally I'd like to have people be able to create `app/models/post.js` with a Post class in it, and that Just Work like it does in Rails.
