### ISSUE TITLE
Add websocket component

### ISSUE THREAD

**Issue by j-f1** [ArtOfCode-/nails#6]
This will use [socket.io](https://socket.io/).

**Comment by ArtOfCode-** [comment]
@j-f1 I think `websocket` is already in the dependencies, which I picked because integration with the Node HTTP server seemed pretty easy.

**Comment by j-f1** [comment]
We could also try to clone ActionCable.

**Comment by ArtOfCode-** [comment]
Heh, that's a whole project in itself. Let's start by using a pre-made solution so we can get major features into Nails. I made a start on models and database stuff a few days ago, but it was terrible, so that also needs to be re-worked at some point.
